version: '3.8' 

services:
  fastapi-pdf: 
    build: .

    container_name: ${CONTAINER_NAME_CUSTOM:-fastapi_pdf_service}
    volumes:
      - ./data/uploads:/app/data/uploads
      - ./data/summaries:/app/data/summaries
      - bobia_data:/app/data
      - bobia_zips:/app/processed_zips
    ports:
      - "${FASTAPI_PDF_HOST_PORT:-8000}:8000"
    environment:
      - UPLOAD_DIR=/app/data/uploads
      - SUMMARY_DIR=/app/data/summaries
    env_file:
      - .env

volumes:
  bobia_data:
  bobia_zips: