version: '3.12-slim'

services:
  fastapi-pdf:
    build: .
    container_name: ${CONTAINER_NAME_CUSTOM:-fastapi_pdf_service}
    ports:
      - "${FASTAPI_PDF_HOST_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      - UPLOAD_DIR=/app/data/uploads
      - SUMMARY_DIR=/app/data/summaries
      - SECRET_KEY=rafa2802 
      - TZ=America/Sao_Paulo
    volumes:
      - ./data/uploads:/app/data/uploads
      - ./data/summaries:/app/data/summaries
      - ./app_data:/app/data                 
      - ./processed_zips:/app/processed_zips 
      - ./backups:/app/backups               
